# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Morgan Open Data Working Symposium"
email: "Info@MorganOpenData.Net"
description: "This one-day symposium brings together a diverse cross-section of scholars, practitioners, entrepreneurs, advocates and policymakers to demonstrate and critique some of the various tools, applications, benefits and
pitfalls of open data, and to a lesser extent big data. Specific focus is on civic engagement and sustainable
development in Africa the African diaspora. "
baseurl: ""
url: "https://morganopendata.net"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "Morgan State"
organizerAlternateName: "Morgan State University"
organizerDescription: "This symposium is hosted by the Division of Research and Economic Development (D-RED). It is made possible primarily by D-RED, the Office of the Provost & Division of Academic Affairs and the School of Global Journalism & Communication. Our special thanks and appreciation are reserved for the Office of the President and several internal and external collaborators and sponsors."
organizerEmail: "info@MorganOpenData.net"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.morgan.edu/research_and_economic_development.html"

# Head
metaKeywords: "event, open data, morgan state, google, programming, social innovation, working symposium"
twitterAccount: "@MorganOpenData"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"

# Documents
c4pUrl: "https://goo.gl/forms/7LWZevQzkr9fS6Zj1"
c4sponsorsUrl: "https://goo.gl/forms/7LWZevQzkr9fS6Zj1"



# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Collaborators"}
 - {permalink: "/team/", text: "About Us"}
 - {permalink: "/logistics/", text: "Direction & Parking"}
 #- {permalink: "/blog/", text: "Blog"}

bottomNavigationLinks:
 - {link: "https://goo.gl/forms/7LWZevQzkr9fS6Zj1", text: "Register"}
rightNavigationButtons:
 - {link: "https://goo.gl/forms/7LWZevQzkr9fS6Zj1", text: "Register"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Morgan Open Data Working Symposium <br /><typeout>"
eventDate: "November 18th, 2016"
typeoutTextValues: '"Acting Local.", "Serving Global."'
typeoutFallback: "Acting Local. Serving Global."
heroButtons:
 - {link: "https://goo.gl/forms/7LWZevQzkr9fS6Zj1", text: "Register"}

# About Block
aboutTitle: "About The Symposium"
aboutBlock:
 - {title: "Workshops", image: "workshop.jpg", text: "A user-centric workshop series focusing on various applications of open data.  We highlight innovative, entrepreneurial and action-oriented approaches." }
 - {title: "Conference", image: "conference.jpg", text: "This one-day symposium brings together a diverse cross-section of scholars, practitioners, entrepreneurs, advocates and policymakers to demonstrate and critique some of the various tools, applications, benefits and pitfalls of open data, and to a lesser extent big data. Specific focus is on civic engagement and sustainable development in Africa and the African diaspora."}
 - {title: "Demonstrations", image: "hackathon.jpg", text: "An opportunity for scholars, advocates and business partners (big and small) to demonstrate their projects, products and services relating to big data, open data, public data & open source." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "30", specialCharacter: "+", info: "collaborators", detail: ""}
 - {count: "8", specialCharacter: "+", info: "hours", detail: ""}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: ""}
 - {count: "5", specialCharacter: "", info: "parallel tracks", detail: ""}

# Latest News Block
latestNewsTitle: "Learn More"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Collaborators"
rockstarSpeakersButtonText: "See all collaborators"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Morgan School of Business & Management"
eventLocationLink: "http://www.morgan.edu/sbm"
eventStreetAddress: "4100 Hillen Rd"
eventAddressLocality: "Baltimore"
eventAddressLocalityRegion: "Maryland"
eventPostalCode: "21218"
eventAddressCountry: "United Stated"
eventStartTime: "2016-11-18T08:00"
eventDoorTime: "08:45"
eventEndTime: "2016-11-18T17:00"
eventPlaceCoordinates: "39.340012, -76.588008"
mapCenterCoordinates: "39.340012, -76.588008"
mapMobileCenterCoordinates: "39.340012, -76.588008"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpeg"
venueTitle: "School of Business & Management"
venueFeatures: ["Parking is $3 per day. Park at the University Student Center. ADA Compliant, Please submit your request when registering."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
#tweetsFeedTitle: "MorganLeads"
twitterHashTag: "MorganOpenData"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
#partnersTitle: "Partners"
partnersC4sponsorsButton: "Register As An Organizer"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Contact Us For Updates"
subscribeAction: "https://formspree.io/info@morganopendata.net"
subscribeInfo: "Please stay tuned!"

# Tickets Block
#ticketsTitle: "Pricetable"
#ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
#ticketsOffers:
# -
#  name: "Early Bird"
#  price: "350"
#  priceCurrency: "UAH"
#  ticketsNumber: "150"
#  ribbon: "-5%"
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-25T10:00"
#  validThrough: "2014-09-30T23:59"
 #-
#  name: "Last Chance"
#  price: "450"
#  priceCurrency: "UAH"
#  ticketsNumber: "100"
#  ribbon: "-20%"
#  featured: true
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-10-01T00:00"
#  validThrough: "2014-10-23T23:59"
#  disabled: true
# -
#  name: "Student"
#  price: "200"
#  priceCurrency: "UAH"
#  ticketsNumber: "50"
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-23T23:59"
#  soldOut: true
#  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/search?f=tweets&q=%23MorganOpenData", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://MorganOpenData.net", text: "Morgan Open Data"}
   - {link: "http://www.morgan.edu", text: "Morgan State University"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@morganopendata.net", text: "info@morganopendata.net"}
 

# Blog
blogTitle: "Our Work"
blogCommentsEnabled: true
discusShortName: "MorganOpenData"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: <p>This symposium is hosted by the <a href="http://www.morgan.edu/research_and_economic_development.html">Division of Research and Economic Development (D-RED)</a>. It is made possible primarily by D-RED, the <a herf="http://www.morgan.edu/academic_affairs.html">Office of the Provost & Division of Academic Affairs</a> and the <a href="http://www.morgan.edu/sgjc">School of Global Journalism & Communication</a>. Our special thanks and appreciation are reserved for the <a href="http://www.morgan.edu/president">Office of the President</a> and several internal and external collaborators and sponsors. <br /><br /> The symposium is designed and organized by <a href="https://www.linkedin.com/in/umarubah">Dr. Umaru Bah</a>, Associate Professor in the Department of Strategic Communication at School of Global Journalism & Communication.  It is part of a strategy geared toward the establishment of a Morgan Center for Open Data Education & Entrepreneurship (M-CODE2). <br /><br />In close collaboration with <a href="http://www.morgan.edu/research_and_economic_development/timothy_akers.html">Dr. Timothy Akers</a>, Assistant VP for Research Innovation & Advocacy, the symposium is structured to demonstrate the benefits and challenges of open data for civic engagement and sustainable development locally and globally. The symposium further serves as an opportunity to showcase Morgan State University as a well-positioned institutional partner for local and global data initiatives, academic enhancement, and research, with focus on minorities in the United States and abroad.<br /><br />It is also structured to demonstrate in content and practice the characteristics for optimal productivity in a global, open-sourced learning ecosystem. These include, across research, teaching and service activities, local and global interdisciplinary collaboration, public-private partnership, grantsmanship and entrepreneurship, user-centered designs and outcomes that privilege and facilitate community engagement and empowerment.<br /><br />This Morgan Open Data Working Symposium will scale up to a Morgan Open Data Working Conference in March 2017, with wider national and international participation and focus. We hope to leverage the networks, feedback and support therefrom to develop and submit the M-CODE2 Center grant proposal in June 2017. <br /><br />We welcome your participation and feedback. Feel free to <a href="mailto:info@morganopendate.net">contact us</a> with suggestions and inquiries.</p>
# Logistics Find Way Block
findWayTitle: "<b>Find your way here</b>"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "39.340012, -76.588008"
logisticsMapMobileCenterCoordinates: "39.340012, -76.588008"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Getting to Morgan"
directionDetailsCards:
 - {title: "From the Student Center Garage", information: 'The Earl G. Graves School of Business & Management is located at 21251, 4100 Hillen Rd, Baltimore, MD 21218. There are limited free parking spaces on the streets and nearby parking lots. To avoid parking-related hassles, we strongly recommend that you park at the Student Center Garage, located at the University Student Center. Parking fee is fifty cents per hour, capped at $3 per day. It is a walking distance from there to the School of Business & Management'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Registration"
    links:
     - {link: "https://goo.gl/forms/7LWZevQzkr9fS6Zj1", text: "Register Here"}
   -
    title: "Attendance Details"
    links:
     - {link: "mailto:info@morganopendata.net", text: "Contact the Coordinator"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
